<a href="https://colab.research.google.com/github/seplanas/valores-nulos-act-2.1/blob/main/Actividad_2_1_(Valores_Nulos).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('/content/Ventas_totales.csv')
data.head(5)

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08,1.023010e+07,6864575.384,9047205.493,...,6705475.318,9.459063e+05,2880656.169,2606192.942,1.050314e+06,340777.3882,4397543.671,772371.8476,1838507.096,2806660.309
1,01/02/2017,25994.2,25223.4,25994200.17,25749179.40,245020.769,25994200.17,9.719067e+06,6438494.011,8309150.301,...,6576624.803,9.256186e+05,2855639.900,2600083.591,1.026167e+06,328288.6951,4053283.771,672290.5165,1257661.903,2354084.901
2,01/03/2017,27780.0,26334.3,27780006.52,27472228.72,307777.804,27780006.52,1.024444e+07,6908522.962,8845010.494,...,7437264.174,1.016148e+06,3188259.169,2824976.726,1.075526e+06,353335.1548,4354197.611,667696.6653,1305674.917,2266189.277
3,01/04/2017,29134.3,27045.9,29134272.22,28827479.49,306792.733,29134272.22,1.031263e+07,7454251.800,9458166.682,...,8211244.093,1.132396e+06,3257140.159,3006158.760,1.037213e+06,359694.4537,4355706.646,838948.2458,1535726.345,2146755.887
4,01/05/2017,27969.0,25631.9,27969004.68,27569311.41,399693.262,27969004.68,1.014761e+07,6735747.319,9220929.862,...,7651058.084,1.033082e+06,3232635.767,2799142.123,9.826512e+05,336568.0085,4206101.605,915895.1498,1824462.036,2117971.483

In [ ]:
valores_nulos=data.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            6
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

In [ ]:
#todos son float por lo que se van a tratar como valores numéricos
data.info()

In [ ]:
data1 = data.copy()

In [18]:
#Se sustituyen los valores nulos de la columna salon_ventas y la de
#subtotal_ventas_alimentos_bebidas usando la mediana.
#Esto con la finalidad de evitar algún tipo de sesgo por valores atípicos.

data1["salon_ventas"]=data1["salon_ventas"].fillna(
    round(data["salon_ventas"].median(),1)
    )
data1["subtotal_ventas_alimentos_bebidas"]=data1["subtotal_ventas_alimentos_bebidas"].fillna(
    round(data["subtotal_ventas_alimentos_bebidas"].median(),1)
    )

In [19]:
#Se verifica que efectivamente no hay valores nulos en la columna salon_ventas
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           1
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                2
panaderia                              0
lacteos                                0
carnes                                 1
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
otros                                  4
dtype: int64

In [ ]:
#Se sustituyen los valores de bebidas, panaderia y lácteos usando la media
#Se escoge la media debido a que es la medida más robusta en estos casos.
#Dado que son elementos con alto volumen de ventas, un solo outlier no va a
#afectar de manera significativa los resultados.
data1["bebidas"]=data1["bebidas"].fillna(
    round(data["bebidas"].mean(),1)
    )
data1["panaderia"]=data1["panaderia"].fillna(
    round(data["panaderia"].mean(),1)
    )
data1["lacteos"]=data1["lacteos"].fillna(
    round(data["lacteos"].mean(),1)
    )

In [ ]:
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            0
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 0
almacen                                 2
panaderia                               0
lacteos                                 0
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

In [16]:
#Para las tarjetas se usó el método de rellenar con un string en concreto.
#Esto con la intención de conocer las tarjetas que fueron imputadas y evitar
#de esta manera confusiones entre si la tarjeta fue imputada o no. Así como si la
#misma es de crédito o de débito.
data1["tarjetas_debito"] =data1["tarjetas_debito"].fillna("8888 8888 8888")
data1["tarjetas_credito"] =data1["tarjetas_credito"].fillna("0000 0000 0000")

In [25]:
#Para la categoría de otros opté por rellenar con el valor de 0 dado que no se
#a que se refiera y no quiero que sea un valor que pueda influir
#de ninguna manera.

data1["otros"]= data["otros"].fillna(0)
data1["otros_medios"]= data["otros_medios"].fillna(0)

In [29]:
#A las columnas de almacen, carnes y verdulerías se les aplicó un ffill
#que es un llenado del ultimo valor no nulo hacia adelante
data1["almacen"] =data1["almacen"].fillna(method="ffill")
data1["carnes"] =data1["carnes"].fillna(method="ffill")
data1["verduleria_fruteria"] =data1["verduleria_fruteria"].fillna(method="ffill")

In [32]:
#A las columnas de alimentos_preparados_rotiseria, indumentario_calzados_textiles_hogar
# y a electronicos_articulos_hogar, se les aplicó un back fill que significa que el valor nulo se imputa por el siguiente valor no nulo
data1["alimentos_preparados_rotiseria"] =data1["alimentos_preparados_rotiseria"].fillna(method="bfill")
data1["indumentaria_calzado_textiles_hogar"] =data1["indumentaria_calzado_textiles_hogar"].fillna(method="bfill")
data1["electronicos_articulos_hogar"] =data1["electronicos_articulos_hogar"].fillna(method="bfill")

In [35]:
#Podemos corroborar que no queda ningún valor nulo dentro del código
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           0
otros                                  0
dtype: int64

In [34]:
#Se convierte el df data1 en un archivo .csv
data1.to_csv('VentasTotalesLimpio')